# Generated by Django 4.0.4 on 2022-06-22 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255, verbose_name='品牌名称')),
                ('brand_site', models.CharField(max_length=255, verbose_name='品牌官网')),
                ('brand_icon', models.CharField(max_length=255, verbose_name='品牌图片路径')),
            ],
            options={
                'verbose_name': '商品品牌',
                'verbose_name_plural': '商品品牌',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('customer_code', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='客户名称')),
                ('customer_name', models.CharField(max_length=255, verbose_name='客户姓名')),
                ('customer_phone', models.CharField(max_length=255, verbose_name='客户电话')),
                ('customer_address', models.CharField(max_length=255, verbose_name='客户手机号')),
            ],
            options={
                'verbose_name': '客户信息',
                'verbose_name_plural': '客户信息',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_code', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='商品代码')),
                ('item_name', models.CharField(max_length=255, verbose_name='商品名称')),
                ('item_model', models.CharField(max_length=255, verbose_name='商品型号')),
                ('item_unit', models.CharField(max_length=255, verbose_name='计量单位')),
                ('item_marketPrice', models.CharField(max_length=255, verbose_name='市场价')),
                ('item_costPrice', models.CharField(max_length=255, verbose_name='成本价')),
                ('item_icon', models.CharField(max_length=255, verbose_name='略缩图路径')),
                ('item_introduction', models.CharField(max_length=255, verbose_name='商品介绍')),
                ('item_stock', models.CharField(max_length=255, verbose_name='商品库存')),
                ('item_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.brand', verbose_name='商品品牌')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='ItemClassify',
            fields=[
                ('classify_code', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='分类编号')),
                ('classify_name', models.CharField(max_length=255, verbose_name='分类名称')),
                ('classify_icon', models.CharField(max_length=255, verbose_name='分类图片路径')),
                ('classify_super', models.CharField(default='0', max_length=255, verbose_name='父级编号')),
            ],
            options={
                'verbose_name': '商品分类分级',
                'verbose_name_plural': '商品分类分级',
            },
        ),
        migrations.CreateModel(
            name='ItemSpec',
            fields=[
                ('spec_code', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='商品规格编号')),
                ('spec_name', models.CharField(max_length=255, verbose_name='商品规格名称')),
            ],
            options={
                'verbose_name': '商品规格',
                'verbose_name_plural': '商品规格',
            },
        ),
        migrations.CreateModel(
            name='ItemSupplier',
            fields=[
                ('supplier_code', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='供应商编号')),
                ('supplier_name', models.CharField(max_length=255, verbose_name='供应商名称')),
                ('supplier_contact', models.CharField(max_length=255, verbose_name='供应商联系人')),
                ('supplier_phone', models.CharField(max_length=255, verbose_name='供应商电话')),
                ('supplier_profile', models.CharField(max_length=255, verbose_name='供应商简介')),
            ],
            options={
                'verbose_name': '商品供应商',
                'verbose_name_plural': '商品供应商',
            },
        ),
        migrations.CreateModel(
            name='ItemToItemSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_value', models.CharField(max_length=255, verbose_name='规格值')),
                ('item_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.item', verbose_name='商品代码')),
                ('spec_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.itemspec', verbose_name='规格编号')),
            ],
            options={
                'verbose_name': '商品--商品规格',
                'verbose_name_plural': '商品--商品规格',
                'unique_together': {('item_code', 'spec_code')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_code', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='订单编号')),
                ('order_totalCost', models.CharField(max_length=255, verbose_name='订单总金额')),
                ('order_date', models.CharField(max_length=255, verbose_name='订购时间')),
                ('order_postalCode', models.CharField(max_length=255, verbose_name='邮编')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('orderDetail_code', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='订单明细编号')),
                ('order_count', models.CharField(max_length=255, verbose_name='订购数量')),
                ('order_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.order', verbose_name='订单号')),
            ],
            options={
                'verbose_name': '订单明细',
                'verbose_name_plural': '订单明细',
            },
        ),
        migrations.CreateModel(
            name='qiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='类型编号')),
                ('age', models.IntegerField(verbose_name='类型名称')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('sc', models.ManyToManyField(to='index.course')),
            ],
        ),
        migrations.CreateModel(
            name='qiao2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='桥梁名称')),
                ('age', models.IntegerField(verbose_name='寿命')),
                ('waijian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.qiao')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='item_classify',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.itemclassify', verbose_name='商品分类分级'),
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('true_price', models.CharField(max_length=255, verbose_name='真实价格')),
                ('item_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.item', verbose_name='商品编号')),
                ('item_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='index.itemtoitemspec', verbose_name='商品规格')),
                ('order_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.orderdetail', verbose_name='订单明细编号')),
                ('supplier_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.itemsupplier', verbose_name='供应商编号')),
            ],
            options={
                'verbose_name': '正在供应的商品',
                'verbose_name_plural': '正在供应的商品',
                'unique_together': {('item_code', 'supplier_code', 'item_spec')},
            },
        ),
        migrations.CreateModel(
            name='haizi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('qiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.qiao')),
                ('qiao2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.qiao2')),
            ],
            options={
                'unique_together': {('qiao', 'qiao2')},
            },
        ),
    ]
