# Generated by Django 4.0.4 on 2022-06-23 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='item_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myItem', to='index.item', verbose_name='商品编号'),
        ),
    ]
