# Generated by Django 4.0.4 on 2022-06-23 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_remove_student_sc'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='stu',
            field=models.ForeignKey(default=222, on_delete=django.db.models.deletion.CASCADE, related_name='stu', to='index.student', verbose_name='学生'),
            preserve_default=False,
        ),
    ]
