# Generated by Django 4.0.4 on 2022-06-23 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_course_stu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='stu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu2', to='index.student', verbose_name='学生'),
        ),
    ]
