# Generated by Django 4.0.4 on 2022-06-25 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_alter_course_stu'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.customerinfo', verbose_name='客户'),
        ),
    ]
