# Generated by Django 4.0.4 on 2022-06-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_alter_customerinfo_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now=True, verbose_name='订购时间'),
        ),
    ]
