# Generated by Django 4.0.4 on 2022-06-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_alter_customerinfo_customer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='customer_address',
            field=models.CharField(max_length=255, verbose_name='客户地址'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='orderDetail_code',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='订单明细编号'),
        ),
    ]
