# Generated by Django 4.0.4 on 2022-06-25 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_alter_customerinfo_customer_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply',
            name='order_detail',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='supply_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.supply', verbose_name='上架的供应商品'),
        ),
    ]
